language: ruby
rvm:
  - 2.6.3
#  - ruby-head

services:
  - postgresql

dist:
  - bionic

addons:
  postgresql: "11.2"
  apt:
    packages:
      - postgresql-11

before_install:
  - gem update --system
  - gem install bundler

  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11

script:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:create
  - bundle exec rake db:migrate
#  - bundle exec rspec