language: ruby
rvm:
  - 2.6.3
#  - ruby-head

services:
  - postgresql

dist:
  - bionic

addons:
  postgresql: "11.2"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11

cache:
  directories:
    - vendor/bundle

env:
  global:
    - PGPORT=5433

before_install:
  - gem update --system
  - gem install bundler

#  - sudo apt-get update
#  - sudo apt-get --yes remove postgresql\*
#  - sudo apt-get install -y postgresql-11 postgresql-client-11
#  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
#  - sudo service postgresql restart 11
#  - psql -c 'CREATE DATABASE myapp_test;' -U postgres
#  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  - sudo service postgresql stop
  - sudo service postgresql start 11
  - sudo service postgresql status 11
  - cp config/database.travis.yml config/database.yml
  - ls /var/run/postgresql/

script:
#  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:setup
  - bundle exec rspec