language: ruby
rvm:
  - 2.6.3
#  - ruby-head

services:
  - postgresql

dist:
  - bionic

addons:
  postgresql: "11.2"
  apt:
    packages:
      - postgresql-11

script:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:create
  - bundle exec rake db:migrate
#  - bundle exec rspec