language: ruby
rvm:
  - 2.6.3
#  - ruby-head

notifications:
  email: false

services:
  - postgresql

dist:
  - bionic

addons:
  postgresql: "11.2"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11

cache:
  directories:
    - vendor/bundle

env:
  global:
    - PGPORT=5432

before_install:
  - gem update --system
  - gem install bundler

  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
  - psql -c 'CREATE DATABASE myapp_test;' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres

  - cp config/database.travis.yml config/database.yml

bundler_args: --jobs 3 --retry 3  --without production

script:
  - bundle exec rake db:setup
  - bundle exec rubocop --format simple
  - bundle exec rspec